### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by bertold** [registrobr/rdap#38]
I would like to use an alternate [HTTP client](https://github.com/imroc/req) with the library. Would you be open to accept such contribution? Thank you.

**Comment by rafaeljusto** [comment]
Hi Bertold, the library doesn't enforce the use of the standard HTTP client:
https://github.com/registrobr/rdap/blob/bd4866f18c9dd0ae5b7b8e2371c0203442f4f0e3/transport.go#L136-L138

You could create a wrapper around specific client implementations to satisfy the interface.
